name: ngx-mat-popover

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.17.0
                  cache: 'yarn'

            - uses: actions/cache@v2
              id: angular-cache
              with:
                  path: |
                      .angular/cache
                  key: ${{ runner.os }}-ng-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-ng

            - name: Install dependencies
              run: yarn --pure-lockfile --non-interactive --no-progress

            - name: Run TSLint
              run: yarn lint

            - name: Run tests
              run: yarn test --configuration=ci

            - uses: cypress-io/github-action@v2
              with:
                browser: chrome
                headless: true
                start: yarn serve:prod
                wait-on: 'http://localhost:4200'
                ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

            - name: Build host app
              run: yarn ng build

            - name: Build library
              run: yarn build

            - name: Publish library
              if: github.event_name == 'workflow_dispatch'
              run: yarn publish:lib
